version: '3'
services:
  frontend:
    container_name: app-todo-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app-frontend
    volumes: 
      - ./frontend/src:/app-frontend/src
    # Os `healthcheck` devem garantir que a aplicação
    # está operacional, antes de liberar o container
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5  

  backend:
    container_name: app-todo-backend
    build: ./
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app-backend
    # command: nodemon  
    volumes:
      - ./backend/src:/app-backend/src
    ports:
      - "3001:3001"
    environment:
      DB_HOST: taskdb 
      DB_PORT: 3306
      DB_NAME: task_list_app
      DB_PASSWORD: root
      HOST: 'http://localhost'  
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5  

# Serviço que irá rodar o banco de dados
  taskdb:
    container_name: task_mysql
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s   

# Serviço Redis
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_container           